
version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    environment:
      CC_TEST_REPORTER_ID: 6e4f8c280bdfcb40ff1cf5ff07d39fc6293715e81a6a0d7b54a0acf2b88f401a
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            # Setup Code Climate
            - run:
                name: "Setup Code Climate Test-Reporter"
                command: |
                  # download test reporter as a static binary
                  curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
                  chmod +x ./cc-test-reporter
            # Run tests
            - run: ./cc-test-reporter before-build
            - run: npm run test-ci && ./cc-test-reporter after-build --exit-code $?
  deploy-docs:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: sudo apt-get update && sudo apt-get install -y python-dev
            - run: sudo curl -O https://bootstrap.pypa.io/get-pip.py
            - run: sudo python get-pip.py
            - run: sudo -H pip install awscli --upgrade --ignore-installed six
            - run: npm run deploy-docs
  deploy-npm:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
        - attach_workspace:
            at: ~/repo
        - run:
            name: Authenticate with registry
            command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc
        - run:
            name: Publish package
            command: npm run publish-npm
workflows:
    build-and-deploy:
      jobs:
        - build-and-test
        - deploy-docs:
            requires:
              - build-and-test
            filters:
              branches:
                only: master
        - deploy-npm:
            requires:
              - deploy-docs
            filters:
              branches:
                only: master

